spring.application.name=audit-log-service
spring.datasource.url=jdbc:postgresql://ep-delicate-paper-a4sp243v.us-east-1.aws.neon.tech/user_service_db?sslmode=require
spring.datasource.username=user_service_db_owner
spring.datasource.password=npg_20DtKcixOqFV
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable schema creation
spring.jpa.hibernate.ddl-auto=update
# Show SQL in console (optional, for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8086

# eureka.client.serviceUrl.defaultZone=http://lgvt-service-discovery:8761/eureka/
eureka.client.service-url.defaultZone=https://lgvt-service-discovery.onrender.com/eureka/